/*AUTOGENERATED ACCUMULUS KIT*/
/*Accumulus 0.6 | Copyright 2024 Seth Vance | https://farawayforests.com/projects/accumulus.html*/

document.getElementById("validation_link_html").setAttribute("href", "https://validator.w3.org/check?uri=" + location.href);
document.getElementById("validation_link_css").setAttribute("href", "https://jigsaw.w3.org/css-validator/validator?uri=" + location.href);

const accumulusKitID = "67ff88";
const accumulusDirectives = {
    "motd": "Welcome to Accumulus!",
    "ignorables": ["google", "jquery", "bootstrap", "fontawesome", "lineicons", "ttf", "otf", "accumulus", "67ff88"],
    "categories": ["HTML", "CSS", "JS"],
    "modules": [{
            "name": "HTMLHint",
            "category": "HTML",
            "rulesets": [
                { "method": "fetch", "locator": "%PAGE" }
            ]
        },
        {
            "name": "HTMLInclude",
            "category": "HTML",
            "rulesets": [
                { "method": "fetch", "locator": "[data-include]", "fromattr": "data-include" }
            ]
        },
        {
            "name": "CSSLint",
            "category": "CSS",
            "rulesets": [
                { "method": "filtered", "locator": "%PAGE", "filter": "<style[^>]*>([\\s\\S]*?)<\\/style>", "name": "style" },
                { "method": "fetch", "locator": "link[rel*=stylesheet]", "fromattr": "href" }
            ]
        },
        {
            "name": "ESLint",
            "category": "JS",
            "rulesets": [
                { "method": "filtered", "locator": "%PAGE", "filter": "<script(?![^>]*\\bsrc\\b)[^>]*>([\\s\\S]*?)<\\/script>", "name": "script" },
                { "method": "fetch", "locator": "script[src]", "fromattr": "src" }
            ]
        }
    ]
};